Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2021-11, with the labels that each got.

#319 calendar: Synchronize events consistently
  lib.php
Labels: bug

#316 start_url: Always use a fresh copy if possible
  index.php
  locallib.php
Labels: bug

#325 eslint: remove problematic @package tags
  amd/build/form.min.js.map
  amd/build/toggle_text.min.js.map
  amd/src/form.js
  amd/src/toggle_text.js
Labels: bug

#327 release: v4.1.3
  README.md
  version.php
Labels: bug

#308 Support the use of Zoom's tracking fields
  backup/moodle2/backup_zoom_stepslib.php
  backup/moodle2/restore_zoom_stepslib.php
  classes/task/update_meetings.php
  classes/task/update_tracking_fields.php
  classes/webservice.php
  db/install.xml
  db/tasks.php
  db/upgrade.php
  lang/en/zoom.php
  lib.php
  locallib.php
  mod_form.php
  recreate.php
  settings.php
  version.php
Labels: enhancement

#290 Fix/289 zoom intro
  classes/webservice.php
  lib.php
Labels: bug

#328 restore defunct meetings without failing
  backup/moodle2/restore_zoom_stepslib.php
Labels: bug

#320 lib: Only update Zoom if the name has changed
  lib.php
Labels: bug

#329 release: v4.2
  README.md
  version.php
Labels: bug, enhancement

#333 release: v4.2.1
  README.md
  version.php
Labels: bug
