Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2021-12, with the labels that each got.

#292 Zoom Recordings
  backup/moodle2/backup_zoom_stepslib.php
  classes/task/delete_meeting_recordings.php
  classes/task/get_meeting_recordings.php
  classes/webservice.php
  db/install.xml
  db/tasks.php
  db/upgrade.php
  lang/en/zoom.php
  loadrecording.php
  locallib.php
  mod_form.php
  recordings.php
  settings.php
  showrecording.php
  version.php
  view.php
Labels: enhancement

#337 tracking fields: always synchronize by coalescing to empty array
  classes/task/update_meetings.php
  lib.php
  locallib.php
Labels: bug

#340 Release/v4.3
  README.md
Labels: bug, enhancement

#342 Zoom meeting sync scheduled task is inefficient #321
  db/tasks.php
Labels: bug

#335 Fix issue 334 key for uuid
  classes/task/get_meeting_reports.php
  db/install.xml
  db/upgrade.php
  lib.php
  locallib.php
  participants.php
  report.php
  version.php
Labels: bug

#343 release: v4.3.1
  README.md
  version.php
Labels: bug
