Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2021-06, with the labels that each got.

#263 Improve update_meetings scheduled task (rebase)
  classes/task/update_meetings.php
Labels: bug, enhancement

#267 Issue 266
  view.php
Labels: bug

#269 Adapt mobile app code to Ionic 5
  classes/output/mobile.php
  templates/mobile_view_page_ionic3.mustache
  templates/mobile_view_page_latest.mustache
Labels: enhancement
