Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2021-08, with the labels that each got.

#258 Improvement: Fully support recurring meetings
  amd/build/form.min.js
  amd/build/form.min.js.map
  amd/src/form.js
  backup/moodle2/backup_zoom_stepslib.php
  backup/moodle2/restore_zoom_stepslib.php
  classes/invitation.php
  classes/task/update_meetings.php
  classes/webservice.php
  db/install.xml
  db/upgrade.php
  exportical.php
  index.php
  lang/en/zoom.php
  lib.php
  locallib.php
  mod_form.php
  settings.php
  tests/mod_zoom_invitation_test.php
  version.php
  view.php
Labels: enhancement

#291 Fix/212 Fix DB schema check error
  db/upgrade.php
Labels: bug

#294 release: Changelog v4.0
  README.md
Labels: bug, enhancement
