Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2022-09, with the labels that each got.

#390 Issue281 - New activity setting: Automatic Recording
  amd/build/scheduleforchooser.min.js
  amd/build/scheduleforchooser.min.js.map
  amd/src/scheduleforchooser.js
  backup/moodle2/backup_zoom_stepslib.php
  classes/webservice.php
  db/install.xml
  db/upgrade.php
  lang/en/zoom.php
  lib.php
  locallib.php
  mod_form.php
  settings.php
  version.php
Labels: enhancement

#402 Enhancement/minimize api get user requests
  README.md
  backup/moodle2/restore_zoom_stepslib.php
  classes/task/update_meetings.php
  classes/webservice.php
  exportical.php
  lib.php
  locallib.php
  mod_form.php
  recordings.php
  recreate.php
  settings.php
  view.php
Labels: bug

#405 release: v4.7.0
  README.md
  version.php
Labels: bug, enhancement

#403 Server-to-server OAuth #387
  README.md
  classes/task/delete_meeting_recordings.php
  classes/task/get_meeting_recordings.php
  classes/task/get_meeting_reports.php
  classes/task/update_meetings.php
  classes/task/update_tracking_fields.php
  classes/webservice.php
  db/caches.php
  lang/en/zoom.php
  lib.php
  settings.php
  tests/generator/lib.php
  tests/mod_zoom_webservice_test.php
Labels: enhancement

#407 mod_form: Also call moodleform_mod parent methods
  mod_form.php
Labels: bug

#410 release: v4.8.0
  README.md
  version.php
Labels: bug, enhancement
