Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2022-04, with the labels that each got.

#363 Allow site-level and activity-level configuration of visible sections on the activity view page
  backup/moodle2/backup_zoom_stepslib.php
  db/install.xml
  db/upgrade.php
  lang/en/zoom.php
  mod_form.php
  settings.php
  version.php
  view.php
Labels: enhancement

#367 Feature/option webinar by default
  lang/en/zoom.php
  mod_form.php
  settings.php
  tests/advanced_passcode_test.php
  tests/error_handling_test.php
  tests/get_meeting_reports_test.php
  tests/mod_zoom_grade_test.php
  tests/mod_zoom_invitation_test.php
  tests/mod_zoom_webservice_test.php
Labels: bug, enhancement

#368 release: v4.4.0
  README.md
  version.php
Labels: bug, enhancement

#370 Add zoom reset function
  lang/en/zoom.php
  lib.php
Labels: enhancement

#372 release: v4.5.0
  README.md
  version.php
Labels: enhancement

#375 Revert icon.svg for pre-moodle 4.0 activity icon
  pix/icon.svg
Labels: bug

#376 release: v4.5.1
  README.md
  version.php
Labels: bug
