Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2022-11, with the labels that each got.

#412 Add a registration feature to the Zoom plugin
  backup/moodle2/backup_zoom_stepslib.php
  classes/webservice.php
  db/install.xml
  db/upgrade.php
  lang/en/zoom.php
  locallib.php
  mod_form.php
  settings.php
  version.php
  view.php
Labels: enhancement

#425 release: v4.9.0
  README.md
  version.php
Labels: bug, enhancement

#426 Fix/webservice error handling
  classes/webservice.php
Labels: bug

#422 Performance: Reduce API calls, respect host's settings
  classes/webservice.php
  mod_form.php
  view.php
Labels: bug

#427 form: Start time in 5 minute intervals; default +1 hour
  mod_form.php
Labels: bug
