Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2023-08, with the labels that each got.

#499 form: add required Promise.then() parameter
  amd/build/form.min.js
  amd/build/form.min.js.map
  amd/src/form.js
Labels: bug

#507 pre-registration: skip grading/completion
  locallib.php
Labels: bug

#509 Enhancement/show meeting date time on course page
  classes/dates.php
  lang/en/zoom.php
  lib.php
Labels: enhancement

#505 Database upgrade.php and schema consistency
  backup/moodle2/restore_zoom_stepslib.php
  db/install.xml
  db/upgrade.php
  lib.php
  mod_form.php
  settings.php
  version.php
Labels: bug, enhancement

#512 mod_form: match title length validation to zoom's limits
  mod_form.php
Labels: bug

#510 release: v5.1.0
  README.md
  version.php
Labels: bug, enhancement
