Repository ncstate-delta/moodle-mod_zoom, pull requests merged in 2025-05, with the labels that each got.

#654 ci: add Moodle 5.0
  .github/workflows/ci.yml
Labels: bug

#655 Update webservice.php generalized autocreate function
  classes/webservice.php
Labels: bug

#623 Send ical Notifications (Version 2)
  classes/task/send_ical_notifications.php
  db/install.xml
  db/messages.php
  db/tasks.php
  db/upgrade.php
  exportical.php
  lang/en/zoom.php
  settings.php
  version.php
Labels: enhancement

#656 Updated catch to throw error instead of returning false
  lib.php
Labels: bug

#657 release: v5.4.0
  CHANGES.md
  upgrade.txt
  version.php
Labels: bug, enhancement
